---
_extends: .github

repository:
  name: jtox
  description: JVM Tox GUI client using JavaFX
  topics: javafx, toktok, openjfx, gui, tox-client

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Travis CI - Pull Request
          - code-review/reviewable
